/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package leerarchivo;

import java.io.IOException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author callo
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Grafica() {
        initComponents();
        this.setLocationRelativeTo(null);
        mcarga.setVisible(false);
        mresul.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        carga = new javax.swing.JButton();
        clasifica = new javax.swing.JButton();
        limpia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoc = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        previo = new javax.swing.JTextArea();
        Imprecion = new javax.swing.JButton();
        mcarga = new javax.swing.JLabel();
        mresul = new javax.swing.JLabel();
        mresul1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Analizador Lexico Grupo 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        carga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/vecteezy_upload-icon-sign-symbol-design_9992368_258.png"))); // NOI18N
        carga.setText("cargar ");
        carga.setBorder(null);
        carga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaActionPerformed(evt);
            }
        });
        getContentPane().add(carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 60));

        clasifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/transferir.png"))); // NOI18N
        clasifica.setText("clasificar");
        clasifica.setBorder(null);
        clasifica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clasifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificaActionPerformed(evt);
            }
        });
        getContentPane().add(clasifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 60));

        limpia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/limpiar.png"))); // NOI18N
        limpia.setText("limpiar");
        limpia.setBorder(null);
        limpia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiaActionPerformed(evt);
            }
        });
        getContentPane().add(limpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, 60));

        resultadoc.setColumns(20);
        resultadoc.setRows(5);
        jScrollPane1.setViewportView(resultadoc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 280, 230));

        previo.setColumns(20);
        previo.setRows(5);
        jScrollPane2.setViewportView(previo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 280, 228));

        Imprecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imprimir.png"))); // NOI18N
        Imprecion.setText("Imprimir");
        Imprecion.setBorder(null);
        Imprecion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Imprecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprecionActionPerformed(evt);
            }
        });
        getContentPane().add(Imprecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 127, 60));

        mcarga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mcarga.setText("Archivo cargado");
        getContentPane().add(mcarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        mresul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mresul.setText("Resultado");
        getContentPane().add(mresul, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        mresul1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mresul1.setForeground(new java.awt.Color(255, 255, 255));
        mresul1.setText(".");
        getContentPane().add(mresul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   JFileChooser jFileChooser1 = new JFileChooser();
       
        
    private void clasificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificaActionPerformed
    mresul.setVisible(true);

        // TODO add your handling code here:
        try{
        
        probarLexer();
        
        }
        
        catch(IOException ex){
        
        System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_clasificaActionPerformed

    private void cargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaActionPerformed
        // TODO add your handling code here:
         mcarga.setVisible(true);
    
        int iResp;
        String strTexto=null;
        ArrayList<String> alLinea=null;
        FileExplorer fmLeeArchivo=null;
        
        try{
        
               iResp=jFileChooser1.showOpenDialog(this);
               if (iResp==jFileChooser1.APPROVE_OPTION){
               
                   fmLeeArchivo = new FileExplorer();
                   alLinea=fmLeeArchivo.leeArchivo(jFileChooser1.getSelectedFile().toString());
                   
                   if(alLinea.size()>0){
                   
                       for(int i=0; i<alLinea.size(); i++){
                       
                       strTexto=(String)alLinea.get(i);
                       previo.append(strTexto+ "\n");
                       
                       }
                       
                   }
                   
                   
               }
        
        
        }
        catch (Exception ex){
                                              
                       ex.printStackTrace();
                       }
    }//GEN-LAST:event_cargaActionPerformed

    private void limpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiaActionPerformed
        // TODO add your handling code here:
            mcarga.setVisible(false);
            mresul.setVisible(false);
        previo.setText("");
        resultadoc.setText("");
    }//GEN-LAST:event_limpiaActionPerformed

    private void ImprecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprecionActionPerformed
      try{
      String nombre="";
      String grupo="Grupo 3 \n \n";
      String nombre1="Carlos Enrique Guzman Cabrera 9491-20-13013\n \n";
      String nombre2="Diego Antonio Marroquin Lopez 9491-20-7815\n \n";
      JFileChooser file=new JFileChooser();
      file.showSaveDialog(this);
      File guarda =file.getSelectedFile();
      
       if(guarda !=null){
          
          FileWriter save=new FileWriter(guarda+".txt");
          save.append(grupo);
          save.append(nombre1);
          save.append(nombre2);
          save.append(resultadoc.getText());
          save.close();//cierre y guardad
          JOptionPane.showMessageDialog(null,"El archivo se a guardado satisdactoriamente");
       } 
      }catch (IOException ex){
      
              JOptionPane.showMessageDialog(null,"El archivo nose a guardado");
      
      
      }
      
    }//GEN-LAST:event_ImprecionActionPerformed

    
    public void probarLexer() throws IOException{
    
    InformacionAnalisis c= new InformacionAnalisis();
    
    File fichero = new File("fichero.txt");
    PrintWriter Writer;
    
    try{
    
        Writer= new PrintWriter(fichero); 
            Writer.print(previo.getText());
                Writer.close();
    
    }catch(FileNotFoundException ex){
  
    }
    
    Reader reader;
    
    reader = new BufferedReader(new FileReader("fichero.txt"));
    Lexer lexer = new Lexer(reader);
    String Resultado="";
    
    while(true){
    
    Tokens tok=lexer.yylex();
    
    if(tok == null){
    
    resultadoc.setText(Resultado);
    return;
    
    }
    
    switch(tok){
    
        case ERROR:
            Resultado=Resultado+"ERROR LEXICO: "+lexer.lexeme+" "+" "+" Linea: "+c.linea+"\n";
            break;
        case ID: case NUMERO:
            Resultado=Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
            break;
            default:
            Resultado=Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
            break;
    }
    }
    
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Imprecion;
    private javax.swing.JButton carga;
    private javax.swing.JButton clasifica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpia;
    private javax.swing.JLabel mcarga;
    private javax.swing.JLabel mresul;
    private javax.swing.JLabel mresul1;
    private javax.swing.JTextArea previo;
    private javax.swing.JTextArea resultadoc;
    // End of variables declaration//GEN-END:variables
}
