/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package leerarchivo;

import java.io.IOException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintWriter;
import java.io.Reader;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.*;
import javax.swing.JFileChooser;


/**
 *
 * @author callo
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Grafica() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        carga = new javax.swing.JButton();
        clasifica = new javax.swing.JButton();
        limpia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoc = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        previo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Analizador Lexico Grupo 2");

        carga.setText("cargar ");
        carga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaActionPerformed(evt);
            }
        });

        clasifica.setText("clasificar");
        clasifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasificaActionPerformed(evt);
            }
        });

        limpia.setText("limpiar");
        limpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiaActionPerformed(evt);
            }
        });

        resultadoc.setColumns(20);
        resultadoc.setRows(5);
        jScrollPane1.setViewportView(resultadoc);

        previo.setColumns(20);
        previo.setRows(5);
        jScrollPane2.setViewportView(previo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clasifica)
                        .addGap(199, 199, 199)
                        .addComponent(limpia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carga)
                    .addComponent(clasifica)
                    .addComponent(limpia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   JFileChooser jFileChooser1 = new JFileChooser();
       
        
    private void clasificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasificaActionPerformed
        // TODO add your handling code here:
        try{
        
        probarLexer();
        
        }
        
        catch(IOException ex){
        
        System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_clasificaActionPerformed

    private void cargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaActionPerformed
        // TODO add your handling code here:
        
        int iResp;
        String strTexto=null;
        ArrayList<String> alLinea=null;
        FileExplorer fmLeeArchivo=null;
        
        try{
        
               iResp=jFileChooser1.showOpenDialog(this);
               if (iResp==jFileChooser1.APPROVE_OPTION){
               
                   fmLeeArchivo = new FileExplorer();
                   alLinea=fmLeeArchivo.leeArchivo(jFileChooser1.getSelectedFile().toString());
                   
                   if(alLinea.size()>0){
                   
                       for(int i=0; i<alLinea.size(); i++){
                       
                       strTexto=(String)alLinea.get(i);
                       previo.append(strTexto+ "\n");
                       
                       }
                       
                   }
                   
                   
               }
        
        
        }
        catch (Exception ex){
                                              
                       ex.printStackTrace();
                       }
    }//GEN-LAST:event_cargaActionPerformed

    private void limpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiaActionPerformed
        // TODO add your handling code here:
        previo.setText("");
        resultadoc.setText("");
    }//GEN-LAST:event_limpiaActionPerformed

    
    public void probarLexer() throws IOException{
    
    InformacionAnalisis c= new InformacionAnalisis();
    
    File fichero = new File("fichero.txt");
    PrintWriter Writer;
    
    try{
    
        Writer= new PrintWriter(fichero); 
            Writer.print(previo.getText());
                Writer.close();
    
    }catch(FileNotFoundException ex){
  
    }
    
    Reader reader;
    
    reader = new BufferedReader(new FileReader("fichero.txt"));
    Lexer lexer = new Lexer(reader);
    String Resultado="";
    
    while(true){
    
    Tokens tok=lexer.yylex();
    
    if(tok == null){
    
    resultadoc.setText(Resultado);
    return;
    
    }
    
    switch(tok){
    
        case ERROR:
            Resultado=Resultado+"ERROR LEXICO: "+lexer.lexeme+" "+" "+" Linea: "+c.linea+"\n";
            break;
        case ID: case NUMERO:
            Resultado=Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
            break;
            default:
            Resultado=Resultado+"LEXEMA: "+tok+" "+" "+" "+" "+" TOKENS: "+lexer.lexeme+"\n";
            break;
    }
    }
    
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carga;
    private javax.swing.JButton clasifica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpia;
    private javax.swing.JTextArea previo;
    private javax.swing.JTextArea resultadoc;
    // End of variables declaration//GEN-END:variables
}
